<?php

it('renders the booking hero in French', function () {
    $this->get('/fr/rendez-vous')
        ->assertOk()
        ->assertSee('data-booking-hero', false)
        ->assertSee('Rendez-vous', false)
        ->assertSee('Demandez votre créneau de visite technique', false)
        ->assertSee('Formulaire intelligent en quelques minutes.', false)
        ->assertSee('Confirmation par WhatsApp ou téléphone.', false)
        ->assertSee('Note de transparence', false)
        ->assertSee('Demande de créneau uniquement.', false)
        ->assertSee('Validation finale après confirmation directe par GS AUTOBILAN.', false)
        ->assertSee('data-booking-intake', false)
        ->assertSee('Votre demande de passage', false)
        ->assertSee('Centre &amp; prestation', false)
        ->assertSee('GS AUTOBILAN Nkolbisson', false)
        ->assertSee('GS AUTOBILAN Obili Scalom', false)
        ->assertSee('Visite technique périodique', false)
        ->assertSee('Contre-visite', false)
        ->assertSee('Vérification documentaire', false)
        ->assertSee('Renseignement / orientation', false)
        ->assertSee('Votre véhicule', false)
        ->assertSee('Véhicule léger', false)
        ->assertSee('Utilitaire', false)
        ->assertSee('Taxi', false)
        ->assertSee('Auto-école', false)
        ->assertSee('Bus / Transport public', false)
        ->assertSee('Poids lourd', false)
        ->assertSee('Autre', false)
        ->assertSee('Créneau souhaité &amp; vos coordonnées', false)
        ->assertSee('data-booking-date-picker', false)
        ->assertSee('data-booking-calendar', false)
        ->assertSee('Choisir une date', false)
        ->assertSee('Il s’agit d’une préférence. L’heure exacte sera confirmée par l’agence.', false)
        ->assertSee('Documents indispensables', false)
        ->assertSee('Demande de passage enregistrée', false)
        ->assertSee('En attente de validation', false)
        ->assertDontSee('type="date"', false)
        ->assertDontSee('data-booking-fast-pass', false)
        ->assertDontSee('data-booking-mobile-actions', false)
        ->assertDontSee('Vous préférez échanger directement avec un agent ?', false);
});

it('renders the booking hero in English', function () {
    $this->get('/en/booking')
        ->assertOk()
        ->assertSee('data-booking-hero', false)
        ->assertSee('Appointment', false)
        ->assertSee('Request your technical inspection visit slot', false)
        ->assertSee('Smart form in a few minutes.', false)
        ->assertSee('Confirmation by WhatsApp or phone.', false)
        ->assertSee('Transparency note', false)
        ->assertSee('Slot request only.', false)
        ->assertSee('Final validation after direct confirmation by GS AUTOBILAN.', false)
        ->assertSee('data-booking-intake', false)
        ->assertSee('Your visit request', false)
        ->assertSee('Centre &amp; service', false)
        ->assertSee('GS AUTOBILAN Nkolbisson', false)
        ->assertSee('GS AUTOBILAN Obili Scalom', false)
        ->assertSee('Periodic technical inspection', false)
        ->assertSee('Re-inspection', false)
        ->assertSee('Document verification', false)
        ->assertSee('Information / guidance', false)
        ->assertSee('Your vehicle', false)
        ->assertSee('Light vehicle', false)
        ->assertSee('Utility vehicle', false)
        ->assertSee('Taxi', false)
        ->assertSee('Driving school', false)
        ->assertSee('Bus / Public transport', false)
        ->assertSee('Heavy vehicle', false)
        ->assertSee('Other', false)
        ->assertSee('Preferred slot &amp; your details', false)
        ->assertSee('data-booking-date-picker', false)
        ->assertSee('data-booking-calendar', false)
        ->assertSee('Choose a date', false)
        ->assertSee('This is a preference. The exact time will be confirmed by the agency.', false)
        ->assertSee('Required documents', false)
        ->assertSee('Visit request recorded', false)
        ->assertSee('Pending validation', false)
        ->assertDontSee('type="date"', false)
        ->assertDontSee('data-booking-fast-pass', false)
        ->assertDontSee('data-booking-mobile-actions', false)
        ->assertDontSee('Prefer to speak directly with an agent?', false);
});
