<?php

it('renders the services page hero in French', function () {
    $response = $this->get('/fr/services');

    $response
        ->assertOk()
        ->assertSee('data-services-hero', false)
        ->assertSee('images/servicespage/services-hero.png', false)
        ->assertSee('Nos services', false)
        ->assertSee('Des services de visite technique pensés pour la sécurité', false)
        ->assertSee('GS AUTOBILAN accompagne les particuliers', false)
        ->assertSee('Véhicules légers', false)
        ->assertSee('Utilitaires &amp;<br>poids lourds', false)
        ->assertSee('Contre-visite', false)
        ->assertSee('Préparation &amp;<br>orientation', false)
        ->assertSee('data-services-core', false)
        ->assertSee('Nos types de prestations', false)
        ->assertSee('Visite technique périodique', false)
        ->assertSee('Le contrôle principal destiné au suivi réglementaire', false)
        ->assertSee('Contrôle des éléments essentiels', false)
        ->assertSee('Rapport officiel', false)
        ->assertSee('En savoir plus', false)
        ->assertSee('Contre-visite', false)
        ->assertSee('Le passage de contrôle après correction', false)
        ->assertSee('Orientation selon les corrections attendues', false)
        ->assertSee('Comprendre la contre-visite', false)
        ->assertSee('Orientation et préparation au passage', false)
        ->assertSee('Préparation des documents', false)
        ->assertSee('Voir la préparation', false)
        ->assertSee('data-services-vehicles', false)
        ->assertSee('Véhicules pris en charge', false)
        ->assertSee('data-vehicle-profile-tab="vehicule-leger"', false)
        ->assertSee('images/servicespage/light-vehicle.png', false)
        ->assertSee('images/servicespage/utility-vehicle.png', false)
        ->assertSee('images/servicespage/taxi-transport.png', false)
        ->assertSee('images/servicespage/heavy-vehicle.png', false)
        ->assertSee('Pour les véhicules légers', false)
        ->assertSee('30 à 45 minutes', false)
        ->assertSee('Pour les utilitaires', false)
        ->assertSee('35 à 50 minutes', false)
        ->assertSee('Pour les taxis / transport', false)
        ->assertSee('Autorisation de transport / Licence', false)
        ->assertSee('Pour les poids lourds', false)
        ->assertSee('45 à 60 minutes', false)
        ->assertSee('Voir toutes les conditions', false)
        ->assertSee('data-services-technical-matrix', false)
        ->assertSee('Ce que nos contrôles prennent en compte', false)
        ->assertSee('Chaque visite comprend une série de vérifications techniques essentielles', false)
        ->assertSee('1. Freinage', false)
        ->assertSee('État des amortisseurs', false)
        ->assertSee('Éclairage &amp; phares', false)
        ->assertSee('4. Pneumatiques', false)
        ->assertSee('Identification du véhicule', false)
        ->assertSee('Inspection visuelle', false)
        ->assertSee('Alignement / ripage', false)
        ->assertSee('Documents &amp; cohérence administrative', false)
        ->assertSee('data-services-architecture-panel', false)
        ->assertSee('data-services-decision-gate', false)
        ->assertSee('Quel service vous correspond ?', false)
        ->assertSee('Je souhaite effectuer ma visite habituelle', false)
        ->assertSee('Visite technique périodique', false)
        ->assertSee('Je reviens après avoir corrigé des anomalies', false)
        ->assertSee('Contre-visite', false)
        ->assertSee('Je ne sais pas quels documents préparer', false)
        ->assertSee('Orientation &amp; préparation', false)
        ->assertSee('Passez à l’étape suivante', false)
        ->assertSee('Choisissez l’action qui vous convient le mieux.', false)
        ->assertSee('Préparer ma visite', false)
        ->assertSee('Voir nos agences', false)
        ->assertSee('Consulter les tarifs', false)
        ->assertSee('Votre demande de rendez-vous sera confirmée par téléphone ou WhatsApp', false)
        ->assertSee('href="/fr/rendez-vous"', false);

    preg_match('/<section[^>]*data-services-hero[^>]*>.*?<\/section>/s', $response->getContent(), $heroSection);

    expect($heroSection[0] ?? '')
        ->not->toContain('Découvrir nos services')
        ->not->toContain('Prendre rendez-vous')
        ->not->toContain('href="/fr/rendez-vous"');
});

it('renders the services page hero in English', function () {
    $response = $this->get('/en/services');

    $response
        ->assertOk()
        ->assertSee('Our services', false)
        ->assertSee('Technical inspection services designed for safety', false)
        ->assertSee('GS AUTOBILAN supports private motorists', false)
        ->assertSee('Light vehicles', false)
        ->assertSee('Utility &amp;<br>heavy vehicles', false)
        ->assertSee('Re-inspection', false)
        ->assertSee('Preparation &amp;<br>guidance', false)
        ->assertSee('data-services-core', false)
        ->assertSee('Our service types', false)
        ->assertSee('Periodic technical inspection', false)
        ->assertSee('regulatory follow-up and verification', false)
        ->assertSee('Essential component checks', false)
        ->assertSee('Learn more', false)
        ->assertSee('Re-inspection', false)
        ->assertSee('A targeted control visit after correcting', false)
        ->assertSee('Guidance based on expected corrections', false)
        ->assertSee('Understand re-inspection', false)
        ->assertSee('Guidance and preparation before your visit', false)
        ->assertSee('Document preparation', false)
        ->assertSee('View preparation', false)
        ->assertSee('data-services-vehicles', false)
        ->assertSee('Vehicles supported', false)
        ->assertSee('data-vehicle-profile-tab="light-vehicle"', false)
        ->assertSee('images/servicespage/light-vehicle.png', false)
        ->assertSee('images/servicespage/utility-vehicle.png', false)
        ->assertSee('images/servicespage/taxi-transport.png', false)
        ->assertSee('images/servicespage/heavy-vehicle.png', false)
        ->assertSee('For light vehicles', false)
        ->assertSee('30 to 45 minutes', false)
        ->assertSee('For utility vehicles', false)
        ->assertSee('35 to 50 minutes', false)
        ->assertSee('For taxis / transport', false)
        ->assertSee('Transport authorization / licence', false)
        ->assertSee('For heavy vehicles', false)
        ->assertSee('45 to 60 minutes', false)
        ->assertSee('View all conditions', false)
        ->assertSee('data-services-technical-matrix', false)
        ->assertSee('What our inspections take into account', false)
        ->assertSee('Each visit includes a series of essential technical checks', false)
        ->assertSee('1. Braking', false)
        ->assertSee('Condition of shock absorbers', false)
        ->assertSee('Lighting &amp; headlights', false)
        ->assertSee('4. Tyres', false)
        ->assertSee('Vehicle identification', false)
        ->assertSee('Visual inspection', false)
        ->assertSee('Alignment / side slip', false)
        ->assertSee('Documents &amp; administrative consistency', false)
        ->assertSee('data-services-architecture-panel', false)
        ->assertSee('data-services-decision-gate', false)
        ->assertSee('Which service fits your need?', false)
        ->assertSee('I want to complete my regular inspection', false)
        ->assertSee('I am returning after correcting issues', false)
        ->assertSee('Re-inspection', false)
        ->assertSee('I do not know which documents to prepare', false)
        ->assertSee('Guidance &amp; preparation', false)
        ->assertSee('Move to the next step', false)
        ->assertSee('Choose the action that fits you best.', false)
        ->assertSee('Prepare my visit', false)
        ->assertSee('See our agencies', false)
        ->assertSee('View tariffs', false)
        ->assertSee('Your appointment request will be confirmed by phone or WhatsApp', false)
        ->assertSee('href="/en/booking"', false);

    preg_match('/<section[^>]*data-services-hero[^>]*>.*?<\/section>/s', $response->getContent(), $heroSection);

    expect($heroSection[0] ?? '')
        ->not->toContain('Discover our services')
        ->not->toContain('Book an appointment')
        ->not->toContain('href="/en/booking"');
});
