<?php

it('renders the technical inspection hero in French', function () {
    $response = $this->get('/fr/visite-technique');

    $response
        ->assertOk()
        ->assertSee('data-inspection-hero', false)
        ->assertSee('images/inspection/hero-inspection.png', false)
        ->assertSee('Visite Technique', false)
        ->assertSee('Comprendre et réussir votre visite technique', false)
        ->assertSee('Découvrez les contrôles effectués, préparez vos documents', false)
        ->assertSee('Préparer ma visite', false)
        ->assertSee('Prendre rendez-vous', false)
        ->assertSee('Contrôle rigoureux', false)
        ->assertSee('Procédure transparente', false)
        ->assertSee('Équipements professionnels', false)
        ->assertSee('Orientation après contrôle', false)
        ->assertSee('gs-inspection-caution-stripe', false)
        ->assertSee('href="#preparer-ma-visite"', false)
        ->assertSee('href="/fr/rendez-vous"', false)
        ->assertSee('data-inspection-importance', false)
        ->assertSee('Pourquoi la visite technique est essentielle', false)
        ->assertSee('La visite technique contribue à la sécurité de tous usagers', false)
        ->assertSee('Sécurité routière', false)
        ->assertSee('Identifie les défauts pouvant compromettre', false)
        ->assertSee('Prévention des risques', false)
        ->assertSee('La détection précoce des anomalies', false)
        ->assertSee('Conformité du véhicule', false)
        ->assertSee('Vérification technique et documentaire structurée', false)
        ->assertSee('data-inspection-control-points', false)
        ->assertSee('Les principaux points de contrôle', false)
        ->assertSee('Nos équipes vérifient les systèmes essentiels', false)
        ->assertSee('images/inspection/control-braking.svg', false)
        ->assertSee('1. Freinage', false)
        ->assertSee('2. Suspension', false)
        ->assertSee('3. Éclairage et signalisation', false)
        ->assertSee('4. Pneumatiques', false)
        ->assertSee('5. Direction et ripage', false)
        ->assertSee('6. Identification', false)
        ->assertSee('7. Inspection visuelle', false)
        ->assertSee('8. Vérification documentaire', false)
        ->assertSee('data-inspection-process', false)
        ->assertSee('Comment se déroule votre passage ?', false)
        ->assertSee('images/inspection/process-reception.svg', false)
        ->assertSee('Accueil et réception', false)
        ->assertSee('Enregistrement du dossier', false)
        ->assertSee('Passage sur la ligne de contrôle', false)
        ->assertSee('Synthèse des résultats', false)
        ->assertSee('Remise du procès-verbal', false)
        ->assertSee('images/inspection/result-accepted.svg', false)
        ->assertSee('Accepté', false)
        ->assertSee('Contre-visite requise', false)
        ->assertSee('Résultat défavorable', false)
        ->assertSee('data-inspection-preparation', false)
        ->assertSee('Préparez votre passage', false)
        ->assertSee('images/inspection/prep-documents.svg', false)
        ->assertSee('Pièces à présenter', false)
        ->assertSee('Carte grise originale', false)
        ->assertSee('Conseils pratiques', false)
        ->assertSee('Vérifiez le fonctionnement des feux', false)
        ->assertSee('images/inspection/prep-vehicles.svg', false)
        ->assertSee('Ce parcours concerne les véhicules légers', false)
        ->assertSee('La demande en ligne ne constitue pas une confirmation automatique', false)
        ->assertSee('Un dossier complet et un véhicule correctement préparé', false);
});

it('renders the technical inspection hero in English', function () {
    $response = $this->get('/en/technical-inspection');

    $response
        ->assertOk()
        ->assertSee('data-inspection-hero', false)
        ->assertSee('Technical Inspection', false)
        ->assertSee('Understand and complete your technical inspection', false)
        ->assertSee('Discover the checks performed, prepare your documents', false)
        ->assertSee('Prepare my visit', false)
        ->assertSee('Book an appointment', false)
        ->assertSee('Rigorous inspection', false)
        ->assertSee('Transparent process', false)
        ->assertSee('Professional equipment', false)
        ->assertSee('Guidance after inspection', false)
        ->assertSee('href="#prepare-visit"', false)
        ->assertSee('href="/en/booking"', false)
        ->assertSee('data-inspection-importance', false)
        ->assertSee('Why technical inspection is essential', false)
        ->assertSee('Technical inspection contributes to the safety', false)
        ->assertSee('Road safety', false)
        ->assertSee('Identifies defects that may compromise', false)
        ->assertSee('Risk prevention', false)
        ->assertSee('Early detection of anomalies', false)
        ->assertSee('Vehicle compliance', false)
        ->assertSee('Structured technical and document checks', false)
        ->assertSee('data-inspection-control-points', false)
        ->assertSee('Main inspection points', false)
        ->assertSee('Our teams check the vehicle’s essential systems', false)
        ->assertSee('images/inspection/control-braking.svg', false)
        ->assertSee('1. Braking', false)
        ->assertSee('2. Suspension', false)
        ->assertSee('3. Lighting and signals', false)
        ->assertSee('4. Tyres', false)
        ->assertSee('5. Steering and side slip', false)
        ->assertSee('6. Identification', false)
        ->assertSee('7. Visual inspection', false)
        ->assertSee('8. Document verification', false)
        ->assertSee('data-inspection-process', false)
        ->assertSee('How does your visit work?', false)
        ->assertSee('images/inspection/process-reception.svg', false)
        ->assertSee('Welcome and reception', false)
        ->assertSee('File registration', false)
        ->assertSee('Inspection lane passage', false)
        ->assertSee('Result summary', false)
        ->assertSee('Official report handover', false)
        ->assertSee('images/inspection/result-accepted.svg', false)
        ->assertSee('Accepted', false)
        ->assertSee('Re-inspection required', false)
        ->assertSee('Unfavourable result', false)
        ->assertSee('data-inspection-preparation', false)
        ->assertSee('Prepare your visit', false)
        ->assertSee('images/inspection/prep-documents.svg', false)
        ->assertSee('Documents to present', false)
        ->assertSee('Original registration card', false)
        ->assertSee('Practical advice', false)
        ->assertSee('Check that the lights are working', false)
        ->assertSee('images/inspection/prep-vehicles.svg', false)
        ->assertSee('This path covers light vehicles', false)
        ->assertSee('An online request is not an automatic confirmation', false)
        ->assertSee('A complete file and a properly prepared vehicle', false);
});
