<?php

it('renders the tracking hero in French', function () {
    $this->get('/fr/suivi-rendez-vous')
        ->assertOk()
        ->assertSee('data-tracking-hero', false)
        ->assertSee('Suivi de demande', false)
        ->assertSee('Suivez votre demande de rendez-vous', false)
        ->assertSee('Consultez la confirmation de votre rendez-vous et l’état de préparation de votre dossier.', false)
        ->assertSee('data-tracking-hero-notice', false)
        ->assertSee('Ce service ne suit pas votre véhicule en temps réel sur la ligne de contrôle.', false)
        ->assertSee('Il présente uniquement le statut de votre demande de rendez-vous et la préparation de votre dossier.', false)
        ->assertSee('data-tracking-lookup', false)
        ->assertSee('Retrouvez votre demande', false)
        ->assertSee('Saisissez les informations utilisées lors de votre demande de rendez-vous.', false)
        ->assertSee('Référence de demande', false)
        ->assertSee('Téléphone ou numéro WhatsApp', false)
        ->assertSee('Immatriculation du véhicule', false)
        ->assertSee('Suivre ma demande', false)
        ->assertSee('Vous n’avez plus votre référence ?', false)
        ->assertSee('Nous vous aidons à la retrouver', false)
        ->assertSee('data-tracking-result', false)
        ->assertSee('Demande reçue', false)
        ->assertSee('Rendez-vous confirmé', false)
        ->assertSee('Dossier prêt', false)
        ->assertSee('Passage prévu', false)
        ->assertSee('Confirmé', false)
        ->assertSee('Votre passage a été confirmé par l’agence.', false)
        ->assertSee('Télécharger le récapitulatif', false)
        ->assertSee('GS-2026-NK-48192', false)
        ->assertSee('GS AUTOBILAN Nkolbisson', false)
        ->assertSee('Visite technique périodique', false)
        ->assertSee('Véhicule léger', false)
        ->assertSee('LT-123-AB', false)
        ->assertSee('15 août 2026', false)
        ->assertSee('Matin (07h00 – 11h00)', false)
        ->assertSee('+237 678 844 791', false)
        ->assertSee('État du dossier', false)
        ->assertSee('Dossier à compléter', false)
        ->assertSee('Voir les éléments à compléter', false)
        ->assertSee('Prochaine étape', false)
        ->assertSee('Veuillez compléter votre dossier.', false)
        ->assertSee('Écrire sur WhatsApp', false)
        ->assertSee('Appeler l’agence', false);
});

it('renders the tracking hero in English', function () {
    $this->get('/en/appointment-tracking')
        ->assertOk()
        ->assertSee('data-tracking-hero', false)
        ->assertSee('Request tracking', false)
        ->assertSee('Track your appointment request', false)
        ->assertSee('Check your appointment confirmation and document preparation status.', false)
        ->assertSee('data-tracking-hero-notice', false)
        ->assertSee('This service does not track your vehicle in real time on the inspection lane.', false)
        ->assertSee('It only shows your appointment request status and document preparation progress.', false)
        ->assertSee('data-tracking-lookup', false)
        ->assertSee('Find your request', false)
        ->assertSee('Enter the information used when making your appointment request.', false)
        ->assertSee('Request reference', false)
        ->assertSee('Phone or WhatsApp number', false)
        ->assertSee('Vehicle registration', false)
        ->assertSee('Track my request', false)
        ->assertSee('No longer have your reference?', false)
        ->assertSee('We can help you find it', false)
        ->assertSee('data-tracking-result', false)
        ->assertSee('Request received', false)
        ->assertSee('Appointment confirmed', false)
        ->assertSee('File ready', false)
        ->assertSee('Visit planned', false)
        ->assertSee('Confirmed', false)
        ->assertSee('Your visit has been confirmed by the agency.', false)
        ->assertSee('Download the summary', false)
        ->assertSee('GS-2026-NK-48192', false)
        ->assertSee('GS AUTOBILAN Nkolbisson', false)
        ->assertSee('Periodic technical inspection', false)
        ->assertSee('Light vehicle', false)
        ->assertSee('LT-123-AB', false)
        ->assertSee('August 15, 2026', false)
        ->assertSee('Morning (07:00 – 11:00)', false)
        ->assertSee('+237 678 844 791', false)
        ->assertSee('File status', false)
        ->assertSee('File to complete', false)
        ->assertSee('View items to complete', false)
        ->assertSee('Next step', false)
        ->assertSee('Please complete your file.', false)
        ->assertSee('Message on WhatsApp', false)
        ->assertSee('Call the agency', false);
});
