map $http_x_forwarded_proto $gs_forwarded_proto {
    default $http_x_forwarded_proto;
    ''      $scheme;
}

map $http_x_forwarded_host $gs_forwarded_host {
    default $http_x_forwarded_host;
    ''      $host;
}

map $http_x_forwarded_for $gs_forwarded_for {
    default $http_x_forwarded_for;
    ''      $remote_addr;
}
